services:
  - type: web
    name: springsecure-service
    env: docker
    plan: free
    autoDeploy: true
    repo: https://github.com/gunjankumar1983/SpringSecure
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        fromDatabase:
          name: springsecure-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: springsecure-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: springsecure-db
          property: password

databases:
  - name: springsecure-db
    databaseName: springsecure
    user: springsecure
    plan: free
    ipAllowList: []
